src/main/java/net/webvalor/model/comercial/ItemPedido.java
package net.webvalor.model.comercial;

import java.io.Serializable;
import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

@Entity
@Table(name = "item_pedido")
public class ItemPedido implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;
	@Column(nullable = false)
	private Integer quantidade = 1;

	@Column(name = "valor_unitario", nullable = false, precision = 10, scale = 2)
	private BigDecimal valorUnitario = BigDecimal.ZERO;

	@ManyToOne
	@JoinColumn(name = "produto_id", nullable = false)
	private Produto produto;

	@ManyToOne
	@JoinColumn(name = "pedido_id", nullable = false)
	private Pedido pedido;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Integer getQuantidade() {
		return quantidade;
	}

	public void setQuantidade(Integer quantidade) {
		this.quantidade = quantidade;
	}

	public BigDecimal getValorUnitario() {
		return valorUnitario;
	}

	public void setValorUnitario(BigDecimal valorUnitario) {
		this.valorUnitario = valorUnitario;
	}

	public Produto getProduto() {
		return produto;
	}

	public void setProduto(Produto produto) {
		this.produto = produto;
	}

	public Pedido getPedido() {
		return pedido;
	}

	public void setPedido(Pedido pedido) {
		this.pedido = pedido;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ItemPedido other = (ItemPedido) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

	@Transient
	public BigDecimal getValorTotal() {
		
		return this.getValorUnitario().multiply(new BigDecimal(this.getQuantidade()));
	}

	@Transient
	public boolean isProdutoAssociado() {
		return this.getProduto() != null && this.getProduto().getId() != null;
	}

	@Transient
	public boolean isEstoqueSuficiente() {
		return this.getPedido().isEmitido() || this.getProduto().getId() == null 
			|| this.getProduto().getQuantidadeEstoque() >= this.getQuantidade(); 
	}
	
	@Transient
	public boolean isEstoqueInsuficiente() {
		return !this.isEstoqueSuficiente();
	}

}

src/main/java/net/webvalor/model/comercial/Pedido.java
package net.webvalor.model.comercial;

import net.webvalor.model.Usuario;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;

@Entity
@Table(name = "pedido")
public class Pedido implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;

	@NotNull
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_criacao", nullable = false)
	private Date dataCriacao;

	@Column(columnDefinition = "text")
	private String observacao;

	@NotNull
	@Temporal(TemporalType.DATE)
	@Column(name = "data_entrega", nullable = false)
	private Date dataEntrega;

	@NotNull
	@Column(name = "valor_frete", nullable = false, precision = 10, scale = 2)
	private BigDecimal valorFrete = BigDecimal.ZERO;

	@NotNull
	@Column(name = "valor_desconto", nullable = false, precision = 10, scale = 2)
	private BigDecimal valorDesconto = BigDecimal.ZERO;

	@NotNull
	@Column(name = "valor_total", nullable = false, precision = 10, scale = 2)
	private BigDecimal valorTotal = BigDecimal.ZERO;

	@NotNull
	@Enumerated(EnumType.STRING)
	@Column(nullable = false, length = 20)
	private StatusPedido status = StatusPedido.ORCAMENTO;

	@NotNull
	@Enumerated(EnumType.STRING)
	@Column(name = "forma_pagamento", nullable = false, length = 20)
	private FormaPagamento formaPagamento;

	@NotNull
	@ManyToOne
	@JoinColumn(name = "vendedor_id", nullable = false)
	private Usuario vendedor;

	@NotNull
	@ManyToOne
	@JoinColumn(name = "cliente_id", nullable = false)
	private Cliente cliente;

	@Embedded
	private EnderecoEntrega enderecoEntrega;

	@OneToMany(mappedBy = "pedido", cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.LAZY)
	private List<ItemPedido> itens = new ArrayList<>();

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Date getDataCriacao() {
		return dataCriacao;
	}

	public void setDataCriacao(Date dataCriacao) {
		this.dataCriacao = dataCriacao;
	}

	public String getObservacao() {
		return observacao;
	}

	public void setObservacao(String observacao) {
		this.observacao = observacao;
	}

	public Date getDataEntrega() {
		return dataEntrega;
	}

	public void setDataEntrega(Date dataEntrega) {
		this.dataEntrega = dataEntrega;
	}

	public BigDecimal getValorFrete() {
		return valorFrete;
	}

	public void setValorFrete(BigDecimal valorFrete) {
		this.valorFrete = valorFrete;
	}

	public BigDecimal getValorDesconto() {
		return valorDesconto;
	}

	public void setValorDesconto(BigDecimal valorDesconto) {
		this.valorDesconto = valorDesconto;
	}

	public BigDecimal getValorTotal() {
		return valorTotal;
	}

	public void setValorTotal(BigDecimal valorTotal) {
		this.valorTotal = valorTotal;
	}

	public StatusPedido getStatus() {
		return status;
	}

	public void setStatus(StatusPedido status) {
		this.status = status;
	}

	public FormaPagamento getFormaPagamento() {
		return formaPagamento;
	}

	public void setFormaPagamento(FormaPagamento formaPagamento) {
		this.formaPagamento = formaPagamento;
	}

	public Usuario getVendedor() {
		return vendedor;
	}

	public void setVendedor(Usuario vendedor) {
		this.vendedor = vendedor;
	}

	public Cliente getCliente() {
		return cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	public EnderecoEntrega getEnderecoEntrega() {
		return enderecoEntrega;
	}

	public void setEnderecoEntrega(EnderecoEntrega enderecoEntrega) {
		this.enderecoEntrega = enderecoEntrega;
	}

	public List<ItemPedido> getItens() {
		return itens;
	}

	public void setItens(List<ItemPedido> itens) {
		this.itens = itens;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Pedido other = (Pedido) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

	@Transient
	public boolean isNovo() {
		return getId() == null;
	}

	@Transient
	public boolean isExistente() {
		return !isNovo();
	}

	@Transient
	public BigDecimal getValorSubtotal() {
		return this.getValorTotal().subtract(this.getValorFrete()).add(this.getValorDesconto());
	}
	
	@Transient
	public void recalcularValorTotal() {
		BigDecimal total = BigDecimal.ZERO;

		total = total.add(this.getValorFrete()).subtract(this.getValorDesconto());
		this.getItens();
		for (ItemPedido item : this.getItens()) {
			if (item.getProduto() != null && item.getProduto().getId() != null) {
				total = total.add(item.getValorTotal());
			}
		}

		this.setValorTotal(total);
	}

	@Transient
	public void adicionarItemVazio() {
		if (this.isOrcamento()) {
			Produto produto = new Produto();

			ItemPedido item = new ItemPedido();
			item.setQuantidade(1);
			item.setProduto(produto);
			item.setPedido(this);

			this.getItens().add(0, item);
		}
	}

	@Transient
	public boolean isOrcamento() {

		return StatusPedido.ORCAMENTO.equals(this.getStatus());
	}

	public void removerItemVazio() {

		ItemPedido primeiroItem = this.getItens().get(0);

		if (primeiroItem != null && primeiroItem.getProduto().getId() == null) {
			this.getItens().remove(0);
		}

	}

	@Transient
	public boolean isValorTotalNegativo() {
		// TODO Auto-generated method stub
		return this.getValorTotal().compareTo(BigDecimal.ZERO) < 0;
	}

	@Transient
	public boolean isEmitido() {
		return StatusPedido.EMITIDO.equals(this.getStatus());
	}

}

src/main/webapp/template/pedidos/BotoesPedido.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:p="http://primefaces.org/ui">

	<p:toolbar style="margin-top: 20px">
  		<p:toolbarGroup>
  			<p:button value="Novo" outcome="/pedidos/CadastroPedido"/>
  			<p:commandButton value="Salvar" action="#{cadastroPedidoBean.salvar()}"
  			update="@form" />
  		</p:toolbarGroup>
  		
  		<p:toolbarGroup align="right">
  			<p:commandButton value="Emitir" />
  			<p:commandButton value="Cancelar" />
  			<p:commandButton value="Enviar por e-mail" />
  			
  			<p:separator/>
  		
  			<p:button value="Pesquisa" outcome="/pedidos/PesquisaPedidos" />
  		</p:toolbarGroup>
  	</p:toolbar>
  	
</ui:composition>

src/main/webapp/template/pedidos/CapaPedido.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

	<p:panelGrid columns="4" style="width: 100%; margin-top: 20px"
		columnClasses="rotulo, campo, rotulo, campo">
		<p:outputLabel value="Número"
			rendered="#{cadastroPedidoBean.editando}" />
		<h:outputText value="#{cadastroPedidoBean.pedido.id}"
			rendered="#{cadastroPedidoBean.editando}" />

		<p:outputLabel value="Data de criação"
			rendered="#{cadastroPedidoBean.editando}" />
		<h:outputText value="#{cadastroPedidoBean.pedido.dataCriacao}"
			rendered="#{cadastroPedidoBean.editando}">
			<f:convertDateTime pattern="dd/MM/yyyy" />
		</h:outputText>

		<p:outputLabel value="Status" />
		<h:outputText value="#{cadastroPedidoBean.pedido.status}" />

		<p:outputLabel value="Vendedor" for="vendedor" />
		<p:selectOneMenu id="vendedor"
			value="#{cadastroPedidoBean.pedido.vendedor}">
			<f:selectItem itemLabel="selecione" />
			<f:selectItems itemLabel="#{vendedor.nome}" itemValue="#{vendedor}"
				value="#{cadastroPedidoBean.vendedor}" var="vendedor" />
		</p:selectOneMenu>

		<p:outputLabel value="Cliente" for="cliente" />
		<p:autoComplete id="cliente" size="40" dropdown="true"
			value="#{cadastroPedidoBean.pedido.cliente}"
			completeMethod="#{cadastroPedidoBean.listarCliente}" var="cliente"
			itemLabel="#{cliente.nome}" itemValue="#{cliente}"
			forceSelection="true" />

		<p:outputLabel value="Forma de pagamento" for="formaPagamento" />
		<p:selectOneMenu id="formaPagamento"
			value="#{cadastroPedidoBean.pedido.formaPagamento}">
			<f:selectItem itemLabel="Selecione" />
			<f:selectItems value="#{cadastroPedidoBean.formaPagamentos}"
				var="formaPagamentos" itemLabel="#{formaPagamentos.descricao}"
				itemValue="#{formaPagamentos}" />
		</p:selectOneMenu>

		<p:outputLabel value="Valor do frete" for="valorFrete" />
		<p:inputText id="valorFrete" size="10" maxlength="10" styleClass="moeda"
			value="#{cadastroPedidoBean.pedido.valorFrete}">
		<f:convertNumber maxFractionDigits="2" minFractionDigits="2" />
		<p:ajax event="change" process="@this" update="totalPedido" listener="#{cadastroPedidoBean.recalcularPedido}"/>
		</p:inputText>

		<p:outputLabel value="Subtotal" style="font-weight: bold" />
		<h:outputText value="#{cadastroPedidoBean.pedido.valorSubtotal}" style="font-weight: bold" id="subtotalPedido" >
			<f:convertNumber type="currency" />
		</h:outputText>

		<p:outputLabel value="Valor de desconto" for="valorDesconto" />
		<p:inputText id="valorDesconto" size="10" maxlength="10"
			styleClass="moeda" value="#{cadastroPedidoBean.pedido.valorDesconto}">
			<f:convertNumber maxFractionDigits="2" minFractionDigits="2" />
			<p:ajax event="change" process="@this" update="totalPedido" listener="#{cadastroPedidoBean.recalcularPedido}"/>
		</p:inputText>

		<p:outputLabel value="Total do pedido"
			style="font-weight: bold; font-size: 1.1em" />
		<h:outputText value="#{cadastroPedidoBean.pedido.valorTotal}"
			style="font-weight: bold; font-size: 1.1em" id="totalPedido">
			<f:convertNumber type="currency" />
		</h:outputText>
	</p:panelGrid>

</ui:composition>

src/main/webapp/template/pedidos/DadosEntregaPedido.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:p="http://primefaces.org/ui">

	<p:panelGrid columns="4" style="width: 100%" columnClasses="rotulo, campo, rotulo, campo">
		<p:outputLabel value="Data da entrega" for="dataEntrega" />
		<p:calendar id="dataEntrega" size="10" pattern="dd/MM/yyyy" value="#{cadastroPedidoBean.pedido.dataEntrega}"/>
		
		<p:spacer />
		<p:spacer />
	
        <p:outputLabel value="Logradouro" for="entregaLogradouro" />
        <p:inputText id="entregaLogradouro" size="50"  value="#{cadastroPedidoBean.pedido.enderecoEntrega.logradouro}"/>

        <p:outputLabel value="Número" for="entregaNumero" />
        <p:inputText id="entregaNumero" size="5" value="#{cadastroPedidoBean.pedido.enderecoEntrega.numero}" />

        <p:outputLabel value="Complemento" for="entregaComplemento" />
        <p:inputText id="entregaComplemento" size="50"  value="#{cadastroPedidoBean.pedido.enderecoEntrega.complemento}"/>

        <p:outputLabel value="Cidade" for="entregaCidade" />
        <p:inputText id="entregaCidade" size="20" value="#{cadastroPedidoBean.pedido.enderecoEntrega.cidade}"/>

        <p:outputLabel value="Estado" for="entregaEstado" />
        <p:inputText id="entregaEstado" size="20" value="#{cadastroPedidoBean.pedido.enderecoEntrega.uf}" />

        <p:outputLabel value="CEP" for="entregaCep" />
        <p:inputText id="entregaCep" size="10" value="#{cadastroPedidoBean.pedido.enderecoEntrega.cep}"/>
	</p:panelGrid>
  	
</ui:composition>

src/main/webapp/template/pedidos/ItensPedido.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

	<p:dataTable value="#{cadastroPedidoBean.pedido.itens}" var="item"
		id="tabelaItens" rowIndexVar="linha" resizableColumns="true">
		<p:column headerText="SKU" style="text-align: center; width: 100px">

			<h:outputLabel value="#{item.produto.sku}"
				rendered="#{item.produtoAssociado}" />
			<p:inputText size="8" value="#{cadastroPedidoBean.sku}"
				rendered="#{not item.produtoAssociado}">

				<p:ajax event="change" process="@this"
					update="tabelaItens :frmCadastroPedido:totalPedido :frmCadastroPedido:subtotalPedido"
					listener="#{cadastroPedidoBean.carregarProdutoPorSKU}" />
			</p:inputText>
		</p:column>
		<p:column headerText="Produto" resizable="true">
			<h:outputText value="#{item.produto.nome}"
				rendered="#{item.produtoAssociado}" />
			<p:autoComplete styleClass="produto-tabela"
				value="#{cadastroPedidoBean.produtoLinhaEditavel}"
				completeMethod="#{cadastroPedidoBean.completarProduto}"
				var="produto" itemLabel="#{produto.nome}" itemValue="#{produto}"
				forceSelection="true" rendered="#{not item.produtoAssociado}">
				<p:ajax event="itemSelect"
					update="tabelaItens :frmCadastroPedido:totalPedido :frmCadastroPedido:subtotalPedido"
					listener="#{cadastroPedidoBean.carregarProdutoLinhaEditavel}" />
			</p:autoComplete>
		</p:column>
		<p:column headerText="Valor Base"
			style="text-align: right; width: 120px">
			<p:inputText value="#{item.valorUnitario}" size="8">

				<f:convertNumber type="currency" />
			</p:inputText>
		</p:column>
		<p:column headerText="Quantidade"
			style="text-align: center; width: 100px">
			<p:inputText size="7" value="#{item.quantidade}">
				<p:ajax event="change" process="@this"
					update="tabelaItens :frmCadastroPedido:totalPedido :frmCadastroPedido:subtotalPedido"
					listener="#{cadastroPedidoBean.atualizarQuantidade(item, linha)}" />
			</p:inputText>
		</p:column>

		<p:column headerText="Prazo de Entrega (dias)" resizable="true"
			style="text-align: center; width: 100px">
			<p:inputText size="3" maxlength="3" />
		</p:column>

		<p:column headerText="% ICMS" resizable="true"
			style="text-align: center; width: 100px">
			<p:inputText size="3" maxlength="3" />
		</p:column>

		<p:column headerText="% IPI" resizable="true"
			style="text-align: center; width: 100px">
			<p:inputText size="3" maxlength="3" />
		</p:column>

		<p:column headerText="Estoque"
			style="text-align: center; width: 100px">
			<h:outputText value="#{item.produto.quantidadeEstoque}"
				style="#{item.estoqueInsuficiente ? 'color:red;' : ''}" />

			<h:graphicImage library="images" name="alerta.png" id="semEstoque"
				style="vertical-align: bottom; margin-left: 5px"
				rendered="#{item.estoqueInsuficiente}" />

			<p:tooltip for="semEstoque" value="Estoque insuficiente"
				rendered="#{item.estoqueInsuficiente}" />
		</p:column>
		<p:column headerText="Valor total"
			style="text-align: right; width: 100px">
			<h:outputText value="#{item.valorTotal}">
				<f:convertNumber type="currency" />
			</h:outputText>
		</p:column>

		<p:columnGroup type="footer">
			<p:row>
				<p:column colspan="8" footerText="Subtotal"
					style="text-align: right" />
				<p:column style="text-align: right">
					<f:facet name="footer">
						<h:outputText value="#{cadastroPedidoBean.pedido.valorSubtotal}">
							<f:convertNumber type="currency" />
						</h:outputText>
					</f:facet>
				</p:column>
			</p:row>
		</p:columnGroup>
	</p:dataTable>

</ui:composition>

src/main/webapp/template/pedidos/ObservacaoPedido.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:p="http://primefaces.org/ui">

	<h:panelGroup layout="block" style="padding-right: 10px">
		<p:inputTextarea rows="10" style="width: 100%" />
	</h:panelGroup>
  	
</ui:composition>